### PR TITLE
Fixed fences will connect to certain blocks

### LINKED ISSUE #3: Unwanted vanilla fence connections to decorative blocks
Vanilla fences will connect to certain decorative blocks that don't have full block models.

Might be block collision model size related.

原版栅栏方块会连接到一些模型不是完整方块的方块上，也许与方块碰撞箱形状有关。

### PR DESCRIPTION
**Pull request by zrll12**
Fixed #3 by injecting world.level.Block.isExceptionForConnection

### CODE REVIEW

**Review by LocusAzzurro — CHANGES_REQUESTED** [review]
A less hacky way (i.e. without using non-api approch) may be preferred if possible.
Although a more scalable implementation is needed even with current approach.

**Comment by zrll12** [comment]
Vanilla mc uses this method to not let leaves, pumpkin etc. connect to the fence, and I don’t find a api provided by forge.
If more blocks is needed, just add more in if.

**Comment by LocusAzzurro** [comment]
After checking it's confirmed that there is no Forge API extention available for this for current version. But since assigning shapes that more or less reflect the actual model shapes is needed nonetheless, we'll just go with defining shapes and let vanilla logic decide the fence connectivity.

**Comment by LocusAzzurro** [comment]
alternate fix found with #19

**Pull request closed without merging**
